### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Gol4nTreviz3** [udaytonapps/flashcards#1]
Hi. When I load this project to my php web hosting, I get a blank page.

**Comment by davidpbauer** [comment]
This is a tool intended to be installed in an instance of Tsugi (https://github.com/tsugiproject). Are you using this with Tsugi?

**Comment by Gol4nTreviz3** [comment]
No I wasn't. I have deployed TSUGI and imported your tool, and now it works fine. Many thanks!
